### ISSUE TITLE
Make new release

### ISSUE THREAD

**Issue by rasmushenningsson** [dillondaudert/NearestNeighborDescent.jl#28]
Could you make a new release? Currently, compat with `Reexport` version 1 is only on master.

**Comment by rasmushenningsson** [comment]
Bump. It would be great if you could make a new release since the compat doesn't play well with some other packages at the moment.

**Comment by babaq** [comment]
this also make `UMAP` not compat with other packages

**Comment by juliohm** [comment]
Same here. @dillondaudert are you still maintaining this package? No one is able to use UMAP.jl in recent projects because dependencies are fixed at old versions.

**Comment by dillondaudert** [comment]
I will make a new release next week.

**Comment by dillondaudert** [comment]
See new release v0.3.5
