### ISSUE TITLE
Implementing AbstractGraph interface (from LightGraph)

### ISSUE THREAD

**Issue by bhgomes** [dillondaudert/NearestNeighborDescent.jl#7]
I wonder if it would be possible to implement [this interface](http://juliagraphs.github.io/LightGraphs.jl/latest/developing.html) for the `DescentGraph`. It would be useful to have this interoperability with other graph libraries, especially for something like [GraphPlot](https://github.com/JuliaGraphs/GraphPlot.jl) which I am interested in using in conjunction with this library.

**Comment by dillondaudert** [comment]
It's pretty straightforward to convert a `DescentGraph.indices` and `DescentGraph.distances` to a `SimpleWeightedDiGraph` and plot it that way. The KNN graph does have some special properties (like each vertex has exactly `k` outgoing edges), but I'd have to think more about if it's worth implementing the `AbstractGraph` interface for it. 

One complication is that the graph data is represented differently during execution (a vector of `MaxHeap`s) and after termination (two matrices), and the former is the one I'd really want to be an `AbstractGraph`.

**Comment by dillondaudert** [comment]
To convert to a weighted digraph:
```jl
using NearestNeighborDescent
using SimpleWeightedGraphs

npoints = 20
k = 4
data = rand(5, npoints)
descgraph = DescentGraph(data, k)

sources = vcat([repeat([i]; outer=k) for i in 1:npoints]...)
destinations = reshape(descgraph.indices, :)
weights = reshape(descgraph.distances, :)

graph = SimpleWeightedDiGraph(sources, destinations, weights)
```

**Comment by dillondaudert** [comment]
As of v0.3, the knn graphs used by this package are `AbstractGraph`s.
