### ISSUE TITLE
Is there a way to increase precision of NN search?

### ISSUE THREAD

**Issue by VPetukhov** [dillondaudert/NearestNeighborDescent.jl#8]
Hi,

I'm testing the package on simulated data with the following code:

```julia
using NearestNeighborDescent
import Distances

test_data = rand(10, 2000)
graph = DescentGraph(test_data, 1, Distances.Euclidean(), max_iters=10000, precision=1e-10, sample_rate=1.0)

nn_per_cell = vec(graph.indices)

real_dists = Distances.pairwise(Distances.Euclidean(), test_data, dims=2);
real_dists[diagind(real_dists)] .= 1e10;
real_nn_per_cell = vec(mapslices(x -> findmin(x)[2], real_dists, dims=1));

nn_real_ids = sum(real_dists .< real_dists[CartesianIndex.(1:length(nn_per_cell), nn_per_cell)], dims=1)

println(mean(real_nn_per_cell .== nn_per_cell))
println(median(nn_real_ids))
```

It's looking for the 1'st NN first using `NearestNeighborDescent` and then by pairwise comparison.

And the output is 

> 0.003
> 467

Which show that only 0.003 of neighbours are really 1'st. And on average it returns 467'th (!) neighbour out of 2000. Am I doing something wrong, or is there a way to change parameters to increase precision?

Just in case, julia v1.1, Distances v0.8.0, NearestNeighborDescent v0.2.0.

**Comment by VPetukhov** [comment]
Just understood that more correct test would be to compare two different sets of data, though it doesn't affect magnitude of the problem:

```julia
using NearestNeighborDescent
import Distances

test_data1 = rand(10, 3000)
test_data2 = rand(10, 1000)

distance = Distances.Euclidean()

graph = DescentGraph(test_data1, 1, distance, max_iters=10000, precision=1e-10, sample_rate=1.0)
nn_per_cell = vec(search(graph, test_data2, 1)[1])

real_dists = Distances.pairwise(distance, test_data1, test_data2, dims=2);
real_nn_per_cell = vec(mapslices(x -> findmin(x)[2], real_dists, dims=1));

nn_real_ids = sum(real_dists' .< real_dists[CartesianIndex.(nn_per_cell, 1:length(nn_per_cell))], dims=1)

println(mean(real_nn_per_cell .== nn_per_cell))
println(mean(nn_real_ids))
```

> 0.001
> 307.92

---

And just for the protocol using FLANN on the same test gives much better results

```julia
import FLANN
## ...
graph = FLANN.flann(test_data1, FLANN.FLANNParameters(), distance);
nn_per_cell = vec(FLANN.knn(graph, test_data2, 1)[1])
## ...
```
> 0.831
> 0.08766666666666667

**Comment by dillondaudert** [comment]
The accuracy of the approximate nearest neighbors is directly related to the size of the candidate neighbors list used during execution. In this case, you've asked for only a single neighbor, so the algorithm does very poorly; increasing that number should improve things.
